### ISSUE TITLE
你好，有关核显驱动问题

### ISSUE THREAD

**Issue by lonzzi** [lunjielee/Opencore-HP-Omen-15-2020#1]
我手上这台是10300H+2060版本，用了这个efi之后核显无法正常驱动，在屏幕变亮后就会卡住，请问有解决方法吗？

**Comment by lunjielee** [comment]
> 我手上这台是10300H+2060版本，用了这个efi之后核显无法正常驱动，在屏幕变亮后就会卡住，请问有解决方法吗？

你好，请你检查一下你的Device ID是否在如下列表中

- 0x3E9B
- 0x3EA5
- 0x3EA6
- 0x3E92
- 0x3E91
- 0x3E98
- 0x9BC8
- 0x9BC5
- 0x9BC4
(我觉得应该是在的）

然后将`AAPL,ig-platform-id`改为`0900A53E`试试

或者去这里WhateverGreen的FAQ寻找Comet Lake然后在里面尝试其他的framebuffer
[https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.IntelHD.en.md](url)

希望能有所帮助！

**Comment by lonzzi** [comment]
你好，
  已经检查Device ID确实在此列表中，改为`0900A53E`这个之后问题依旧，也在WhateverGreen的FAQ里面尝试过其他的framebuffer，问题依旧。
  在最后卡住的地方（用的是原来的platform-id）也看到了核显驱动似乎是成功了，但是并不清楚为什么会卡住，在替换过别人制作的DSDT之后在最后同一个地方卡住但是重启了，我怀疑是DSDT问题，不过对于DSDT我了解甚少，寻找到的一些资料似乎并无帮助，DSDT是否要进行修改，能请教一下这方面的问题吗？

**Comment by lunjielee** [comment]
> 你好，
> 已经检查Device ID确实在此列表中，改为`0900A53E`这个之后问题依旧，也在WhateverGreen的FAQ里面尝试过其他的framebuffer，问题依旧。
> 在最后卡住的地方（用的是原来的platform-id）也看到了核显驱动似乎是成功了，但是并不清楚为什么会卡住，在替换过别人制作的DSDT之后在最后同一个地方卡住但是重启了，我怀疑是DSDT问题，不过对于DSDT我了解甚少，寻找到的一些资料似乎并无帮助，DSDT是否要进行修改，能请教一下这方面的问题吗？

这样的话先注入`12345678`（`AAPL,ig-platform-id`改为`78563412`）点亮屏幕，如果没有卡住的话说明是framebuffer的问题
至于DSDT的话你是从哪里找到的呢？我这个里面全是SSDT而且不推荐使用DSDT来运行黑苹果

**Comment by lonzzi** [comment]
更改了此id之后，启动之后一直在代码阶段，有听到声音，但是没有macos的界面出现，只有启动时的那些代码流动，尝试按了enter键，有听到声音反馈，但也进不去界面。
我这里也确实是SSDT，之所以说了DSDT，是因为之前习惯性的将DSDT和SSDT看成一样的了:(

**Comment by lunjielee** [comment]
> 更改了此id之后，启动之后一直在代码阶段，有听到声音，但是没有macos的界面出现，只有启动时的那些代码流动，尝试按了enter键，有听到声音反馈，但也进不去界面。
> 我这里也确实是SSDT，之所以说了DSDT，是因为之前习惯性的将DSDT和SSDT看成一样的了:(

那就`device-id`注入`9B3E0000`

`AAPL,ig-platform-id`    注入 `  00009B3E` 吧
完整代码如下

`<key>AAPL,ig-platform-id</key>`
`<data>`
`AACbPg==`
`</data>`
`<key>device-id</key>`
`<data>`
`mz4AAA==`
`</data>`

**Comment by lonzzi** [comment]
> > 更改了此id之后，启动之后一直在代码阶段，有听到声音，但是没有macos的界面出现，只有启动时的那些代码流动，尝试按了enter键，有听到声音反馈，但也进不去界面。
> > 我这里也确实是SSDT，之所以说了DSDT，是因为之前习惯性的将DSDT和SSDT看成一样的了:(
> 
> 那就`device-id`注入`9B3E0000`
> 
> `AAPL,ig-platform-id` 注入 ` 00009B3E` 吧
> 完整代码如下
> 
> `<key>AAPL,ig-platform-id</key>`
> `<data>`
> `AACbPg==`
> `</data>`
> `<key>device-id</key>`
> `<data>`
> `mz4AAA==`
> `</data>`

注入之后问题又回到原来的了，屏幕变亮后卡住，不过我注意到一点
IGPU:Ring size: 32 KB
这是说显存只有32KB吗，我又该如何修改

**Comment by lunjielee** [comment]
> > > 更改了此id之后，启动之后一直在代码阶段，有听到声音，但是没有macos的界面出现，只有启动时的那些代码流动，尝试按了enter键，有听到声音反馈，但也进不去界面。
> > > 我这里也确实是SSDT，之所以说了DSDT，是因为之前习惯性的将DSDT和SSDT看成一样的了:(
> > 
> > 
> > 那就`device-id`注入`9B3E0000`
> > `AAPL,ig-platform-id` 注入 ` 00009B3E` 吧
> > 完整代码如下
> > `<key>AAPL,ig-platform-id</key>`
> > `<data>`
> > `AACbPg==`
> > `</data>`
> > `<key>device-id</key>`
> > `<data>`
> > `mz4AAA==`
> > `</data>`
> 
> 注入之后问题又回到原来的了，屏幕变亮后卡住，不过我注意到一点
> IGPU:Ring size: 32 KB
> 这是说显存只有32KB吗，我又该如何修改

那加上这几条吧，用notepad++编辑避免破坏原格式

`<key>framebuffer-fbmem</key>`
`<data>`
`AACQAA==`
`</data>`
`<key>framebuffer-stolenmem</key>`
`<data>`
`AAAwAQ==`
`</data>`
`<key>framebuffer-unifiedmem</key>`
`<data>`
`AAAAgA==`
				`</data>`

**Comment by lunjielee** [comment]
> > 你好，
> > 已经检查Device ID确实在此列表中，改为`0900A53E`这个之后问题依旧，也在WhateverGreen的FAQ里面尝试过其他的framebuffer，问题依旧。
> > 在最后卡住的地方（用的是原来的platform-id）也看到了核显驱动似乎是成功了，但是并不清楚为什么会卡住，在替换过别人制作的DSDT之后在最后同一个地方卡住但是重启了，我怀疑是DSDT问题，不过对于DSDT我了解甚少，寻找到的一些资料似乎并无帮助，DSDT是否要进行修改，能请教一下这方面的问题吗？
> 
> 这样的话先注入`12345678`（`AAPL,ig-platform-id`改为`78563412`）点亮屏幕，如果没有卡住的话说明是framebuffer的问题
> 至于DSDT的话你是从哪里找到的呢？我这个里面全是SSDT而且不推荐使用DSDT来运行黑苹果

这里我弄错了，`AAPL,ig-platform-id`改为`12345678` 不需要大小端转换，保持`device-id`还是`9b3e0000`试试
还不行的话，就等九月发布会吧😂

**Comment by lonzzi** [comment]
> > > 你好，
> > > 已经检查Device ID确实在此列表中，改为`0900A53E`这个之后问题依旧，也在WhateverGreen的FAQ里面尝试过其他的framebuffer，问题依旧。
> > > 在最后卡住的地方（用的是原来的platform-id）也看到了核显驱动似乎是成功了，但是并不清楚为什么会卡住，在替换过别人制作的DSDT之后在最后同一个地方卡住但是重启了，我怀疑是DSDT问题，不过对于DSDT我了解甚少，寻找到的一些资料似乎并无帮助，DSDT是否要进行修改，能请教一下这方面的问题吗？
> > 
> > 
> > 这样的话先注入`12345678`（`AAPL,ig-platform-id`改为`78563412`）点亮屏幕，如果没有卡住的话说明是framebuffer的问题
> > 至于DSDT的话你是从哪里找到的呢？我这个里面全是SSDT而且不推荐使用DSDT来运行黑苹果
> 
> 这里我弄错了，`AAPL,ig-platform-id`改为`12345678` 不需要大小端转换，保持`device-id`还是`9b3e0000`试试
> 还不行的话，就等九月发布会吧😂

上述方法全试了一遍，依旧失败告终，只能等等后续了😂

多谢解答！
