### ISSUE TITLE
15-EK0013DX unable to boot into installer and some other issues found in repo.

### ISSUE THREAD

**Issue by digitalcrossroad** [lunjielee/Opencore-HP-Omen-15-2020#10]
Hi,

I have the [HP Omen 15-EK0013DX](https://www.bestbuy.com/site/hp-omen-15-6-gaming-laptop-intel-core-i7-16gb-memory-nvidia-geforce-rtx-2060-512gb-ssd-32gb-optane-shadow-black/6409146.p?skuId=6409146). 

From what I can see, seems like pretty much same specs as you, except mine came with this Intel HBRPEKNX0202AH SSD instead of the Samsung PM981a one you mentioned in your repo. Nonetheless, I decided to buy/install a 1TB Samsung 970 Evo Plus to put macOS on and leave the factory intel ssd for windows (my machine has two m2 slots).

I started off trying to get Catalina on this machine about a month ago and was making progress but kept getting defeated by 7mb for video memory and couldn't get around that no matter what I configured as platform/device-id in my config.plist for WhateverGreen. When I stumbled upon your guide I got excited and finally thought I can end my pain and suffering. I've been trying to go vanilla as possible, following the opencore guide to the letter, using prebuilt AMLs, and not including anything in my efi that is not needed. The world of building your own AMLs is still foggy for me using hackintool but with some help I'm sure I could figure it out if that's going to be my only solution.

After stumbling upon your guide the other night, I decided to give it a go with Big Sur. 

Let me start by saying unfortunately copying/pasting your efi and updating serial unfortunately wasn't as easy/simple as I expected even though our specs are so similar. I'm wondering if this has to do with me recently updating BIOS and you're possibly running an older version and the mapping of hardware is not aligning with your custom AMLs?

I've enabled all debugging, and I'm not getting a kernel panic, it gets to the point where I expect to see the installer load but then just reboots. https://imgur.com/a/nUUAgSh (make sure to enlarge to see full picture)

In short, given the imgur link above, and how my machine reboots after that message, any idea on how I could further troubleshoot the cause of the reboot? Thanks.

I've tried looking through your commits and config.plist comments on the AMLs to get a better grasp on what these are all for but I'm not sure what to do when the machine isn't even giving an error on why it's rebooting even after enabling all debugging as follows:

Misc
 Quirk | Enabled
-- | --
AppleDebug | YES
ApplePanic | YES
DisableWatchDog | YES
Target | 67

bootargs: -v debug=0x100 keepsyms=1

Notes:

Looks like you recently had and deleted SMCDellSensors in your efi but didn't delete from your config.plist. That was simple enough for me to delete that using propertree.

Second thing I noticed (mainly for others that stumble upon this), various Voodoo kexts kept giving me issues if they were not loaded in the proper order in config.plist. This was in part caused by me doing clean snapshots using propertree and propertree messing up the order. For what it's worth, looks like you have them in the appropriate order where you won't experience a panic. I never experienced such a thing when installing Catalina. When trying to install Catalina I used a mixture of VoodooI2C, VoodooPS2Controller, and VoodooRMI and they just worked without any aml patching or any worries about order in config.plist. Anyway, user beware that if your voodoo kexts are not in the appropriate order of loading in your config.plist when trying to install Big Sur you will see such errors in my experience.

Last but not least, I'm seeing various Booter and Kernel Quirk booleans not quite matching up with your config.plist and the opencore install [guide.](https://dortania.github.io/OpenCore-Install-Guide/config-laptop.plist/coffee-lake-plus.html) I'm not going to go through all of those differences here, but I tried both as you had them set, and how the guide recommends, and no difference in terms of getting installer to boot. (see imgur link above where the machine gets to that state, and then instead of loading installer it reboots, no panic displayed).

**Comment by lunjielee** [comment]
@digitalcrossroad 
Hi, thanks for your humble advice, I will tell the users about the importance of kext loading orders. 

From your description, you have used a 1TB Samsung 970 Evo Plus which is not natively supported by macOS OOB, a [firmware update from Samsung](https://www.samsung.com/semiconductor/minisite/ssd/download/tools/) will allow these drives to operate in macOS ([Form dortania's guide](https://dortania.github.io/Anti-Hackintosh-Buyers-Guide/Storage.html))

**Comment by digitalcrossroad** [comment]
Hi @lunjielee, thanks for getting back. I've already done the FW update. Like I said, I can get into the installer if I build the EFI myself, just not using yours. 

Mainly came looking here for resolving the igpu video memory issue.

"I started off trying to get Catalina on this machine about a month ago and was making progress but kept getting defeated by 7mb for video memory and couldn't get around that no matter what I configured as platform/device-id in my config.plist for WhateverGreen. When I stumbled upon your guide I got excited and finally thought I can end my pain and suffering. I've been trying to go vanilla as possible, following the opencore guide to the letter, using prebuilt AMLs, and not including anything in my efi that is not needed. The world of building your own AMLs is still foggy for me using hackintool but with some help I'm sure I could figure it out if that's going to be my only solution."

FWIW, I'm running F.07 bios, what version are you running? Also, would you mind pointing me to a link that goes over building your own AMLs?

**Comment by lunjielee** [comment]
@digitalcrossroad I'm running F.07 bios as well so that should not be the problem here.
As for building your own AMLs, I suggest you referring to this guide: [Getting Started With ACPI](https://dortania.github.io/Getting-Started-With-ACPI/)
