### ISSUE TITLE
Need help with reaching the installer

### ISSUE THREAD

**Issue by Warmerfare** [lunjielee/Opencore-HP-Omen-15-2020#11]
Hey Lunjielee,

Thanks for sharing your EFI folder for the HP Omen 2020. I just got the same laptop but with a i5-10300H instead of the i7. Only thing is that my machine will not boot to the installer, but instead hangs on the verbose booting screen. Seems like it's an issue with the TextInputMenuAgent.app. I tried to remake the usb installer (thinking this file was currupt), but it came up with the same problem. I attached a photo of the output and really hope you (or someone else) could help me out here.

Thanks in advance!
![IMG_9842](https://user-images.githubusercontent.com/76842342/103440508-8c49ca80-4c46-11eb-8ff7-98a6f0f4605f.jpg)

**Comment by digitalcrossroad** [comment]
@Warmerfare fyi I think this is the same issue I'm experiencing in issue #10 except mine will reboot once it hits this stage instead of hanging.

**Comment by Warmerfare** [comment]
@digitalcrossroad I think it is. I added my own aml files and rebuild the config.plist since my last post, result is that my laptop reboots when it hits this stage now. Made my installer with a Kingston usb2.0 16gb usb to be sure it wasn't due to usb3.0 stuff. Tried Catalina as well, didn't change anything. Will keep looking into a fix for this, may I find it I will post it here. May anyone be able to help I would be really thankful :)

**Comment by Warmerfare** [comment]
@digitalcrossroad @lunjielee It might be related to the bios version since the newer version supports undervolting from the OS now. Could you guys maybe share your bios version so I can check if it's worth the time and hassle to downgrade it?

Thanks in advance!

**Comment by lunjielee** [comment]
@Warmerfare
I'm sorry to tell you that the built-in graphics of i5-10300H is not yet supported by macOS as of 01-07-2021 (So far I see no successful boot using built-in graphics on such a processor.) One thing I can suggest is that you continue to try different framebuffers or plug a supported egpu.

**Comment by Warmerfare** [comment]
@lunjielee Thanks for the response and pointing me into a direction. I've found one succes story on my processor:  [Dell G315 Catalina](https://www.reddit.com/r/hackintosh/comments/i5cuon/dell_g315_fb300f85c_catalina_opencore/)
Seems like there's no issue with using the MacBookPro16,4 identifier. I'll be trying out different framebuffers today and report back to this thread.
Since the iGPU is the well known UHD 630 variant, may I ask what made you think the problem is related to it?

**Comment by Warmerfare** [comment]
@digitalcrossroad  @lunjielee  I don't think the problem is related to the I5-10300H iGPU since it's device-id '0x9BC4'  is natively supported in MacOS (according to Intel's and WhateverGreens info pages). After updating the iGPU patching information in the config.plist to the one corresponding with my iGPU the kernel panic is exactly the same. (textmenuinputagent.kext not found). I can't find anyone else having a similar type of kernel panic, so It will be trail and error to find out what's causing this. If I find anything I'll post it here.

**Comment by digitalcrossroad** [comment]
@Warmerfare I'm running F.07. what about you?

**Comment by lunjielee** [comment]
@Warmerfare Also try to fake the `device-id` to `UHD630`  even though it's device-id '0x9BC4' is natively supported in macOS

And the reason why I think this is a CPU related problem is that I can't guarantee that both i5 and i7 have the same iGPU specs internally even though they do have the same specs on Intel's website (After all, one is called i5 and the other is i7, they can't be exactly the same right?)

**Comment by Warmerfare** [comment]
@digitalcrossroad I'm on F.06. My exact laptop model is : "HP Omen 15-ek0115nd". I don't think downgrading the bios will resolve the issue but I'll keep it open as a option to try out.

You also mentioned that you were able to boot the installer before, but with issue's. Since I wasn't able to boot anything yet till this point, do you mind sharing that EFI folder with me?

@lunjielee I'll try that today with some other device ID's. I faked it to the '0x9BC4' device-id yesterday (the same id as it has from itself) but that didn't make a difference. I also tried different framebuffers, but the GPU support became worse (looking at the verbose boot screen) when changing it. 
You are right about it not being the same CPU and possibly iGPU, and I think the problem must be related to it as well. 
Only weird thing in my opinion is the TextMenuInputAgent.kext crashing (something I really can't find anything about online). And in my mind that doesn't add up with GPU or CPU related problems. (but that again, what do I know about it :P)

**Comment by Warmerfare** [comment]
I found out that my system crashes just before it should load ACPI_SMC_PlatformPlugin - IntelCPUPowerManagement as seen in the screenshot below. This suspects me of the issue involving CPUFriend.kext (which is a CPU power management kext). I'll be reading up on [the instruction sheet](https://github.com/acidanthera/CPUFriend/blob/master/Instructions.md).

Also I found someone else with the I5-10300H and uHD 630 who shared his iGPU patch [here](https://www.olarila.com/topic/12233-eblogexitbsstart-error-opencore-big-sur-111/?tab=comments#comment-138024). He changed his system id to MacBook 16,1 as well. Unfortunately I had no succes with the changes and I'm still stuck at the same part of the verbose screen.

![Screenshot of verbose screen](https://user-images.githubusercontent.com/76842342/104249254-576e1c80-546b-11eb-84c9-8f08beef3e8e.PNG)

**Comment by lunjielee** [comment]
@Warmerfare 
There are a few things that need to be confirmed: 

- [ ] 1. Is your graphics switcher has been switched to `Hybrid` in BIOS?

2. Are you using  `OpenCore`  or `Clover`?

- [ ] 3. Make sure you are not using my version of `CPUFriendDataProvider.kext` cause it is customized for 10750H only (IntelCPUPowerManagement Related)

- [ ] 4. Do not use my AMLs directly unless your ACPI device locations are the same as mine
The guide is here: [Getting Started with ACPI](https://dortania.github.io/Getting-Started-With-ACPI/)
A windows version of AML editor is here: [QtiASL](https://github.com/ic005k/QtiASL/releases)

- [ ] 5. Inject a fake CPUID
A list of CPUIDs can be found here: [x86, x64 Instruction Latency, Memory Latency and CPUID dumps](http://instlatx64.atw.hu/)
Search for `7.5 Emulate Properties` in [OpenCore's Reference Manual](https://github.com/acidanthera/OpenCorePkg/raw/master/Docs/Configuration.pdf)

- [ ] 6. 
![104249254-576e1c80-546b-11eb-84c9-8f08beef3e8e](https://user-images.githubusercontent.com/32808108/104276468-e026a000-54df-11eb-8028-2878fab4229a.png)
Again, these two lines here indicate that GUI init failed (which is a problem related to your GPU)
As for TextMenuInputAgent.kext crashing, I really think it's Apple's problem (Or it may be caused by the GUI init failure, etc)

A dump of your ACPI files and an archive of your EFI folder could be really helpful

**Comment by Warmerfare** [comment]
Dear @lunjielee,

Thanks a lot for the reply, and sorry for my absence (I had some important stuff to do). 

To answer the questions: GPU is set to Hybrid in BIOS, I'm using opencore 0.6.4, CPUFriendDataProvider is deleted (and was the key to overcome some verbose boot errors), AML's are replaced with custom generated ones, CpuID is faked (but not sure if correctly done). The screenshot I supplied is of a virtual machine running MacOS and not natively on the OMEN, just to see what verbose lines would be presented past the error's I got. (I found out about the custom CPU patch this way) GPU acceleration is indeed not supported from this VM.

CURRENT STATUS:

I experimented a bit more and successfully booted into the installer and installed MacOS Big Sur.

I did this by first removing the custom CPU related files from the EFI and config.plist. I replaced the AML's with custom made ones (the ones that could be generated). It still gave me CPU related error during verbose booting and I couldn't get into the installer. 

The EFI folder I use today still got this issue, but I sorta got a fix for it.

If I try to boot a [Legion 5I](https://github.com/LuckyCrack/Legion-5i-EFI) it's EFI folder (ofcourse crashing and having to hold power button) and after that boot with the EFI I downloaded from here (and adjusted a bit) it boots! Only things that are not working when doing this trick is the trackpad, bluetooth, battery and sleep.

I now somehow have to merge those 2 EFI folders in order to have 1 working EFI, but for now this at least allows me to boot into MacOS. After I've accomplished that I can look into the trackpad, bluetooth, battery and sleep fixes.

![Screen Shot 2021-02-18 at 17 11 58](https://user-images.githubusercontent.com/76842342/108386044-8b77f280-720c-11eb-9e23-66a49b882ed6.png)

(these are the value's stored in the NVRAM supplied by Hackintool, any idea how to translate that into my config.plist?)

![Screen Shot 2021-02-18 at 17 14 04](https://user-images.githubusercontent.com/76842342/108386266-c712bc80-720c-11eb-9392-702bd04ced7d.png)

(and this is information about the framebuffer)

(ps. in hackintool it shows my UHD 630 emulated with Iris Plus 655 framebuffer. This framebuffer could be a potential solution to patch the EFI I got from here to work with my system. I will be trying this out tonight.)

**Comment by lonzzi** [comment]
@Warmerfare 

I am using the same laptop as yours, and now I have found the problem.

A few days ago, I found another EFI [LEGION_Y7000Series_Hackintosh](https://github.com/xiaoMGitHub/LEGION_Y7000Series_Hackintosh) and successfully booted with this EFI flies.

<img width="698" alt="截屏2021-02-19 下午1 44 40" src="https://user-images.githubusercontent.com/16703019/108464529-4ced4100-72bb-11eb-8ec7-6cc9e8f42edc.png">

After comparison, I just add two line to the [lunjielee's EFI](https://github.com/lunjielee/Opencore-HP-Omen-15-2020) and all things doing well, the trackpad, bluetooth, battery and sleep fixes.It seems the key to the problem.

<img width="890" alt="截屏2021-02-19 下午1 43 13" src="https://user-images.githubusercontent.com/16703019/108464554-5bd3f380-72bb-11eb-8f37-8da23942ebab.png">

You can try this I have edited [config.plist](https://drive.google.com/file/d/1ymkX_FEvbUBFowzltOm6xkiNa7g6Vgi6/view?usp=sharing) with [lunjielee's EFI](https://github.com/lunjielee/Opencore-HP-Omen-15-2020).

Hopefully this will help you.

**Comment by Warmerfare** [comment]
Thanks a lot for the detailed instructions.

Things I noticed in comparison to my previous EFI folder (previously used Lunjielee's EFI with the CPU specific kexts removed and native UHD 630 support enabled):

CPU - Scores higher with CPU specific kexts removed (about 15 a 20% increase with my last EFI folder)
GPU - Scores higher with the config.plist modification Lonzzi mentioned.

Everything else - Everything works perfectly, except for the video out and mic of course. Totally amazing!

Just activated the iServices as well and completely ready to use xcode on this laptop now!

I'll be removing the CPU specific things tonight to see if I can increase CPU performance. Will be posting that here.

Special thanks to @lunjielee for supplying the EFI folder with ALL the custom aml and kexts files, and for helping me reach further into the verbose screen. And thanks to @lonzzi for supplying me with the final solution. Also @digitalcrossroad , in case you haven't find a solution yet. Try this one out.

**Comment by lunjielee** [comment]
@Warmerfare 
Looks like the problem has been solved, great!
There are a few more things I'd like to clarify:

- Video out
It may never work. We will have to wait to see when Apple decides to support Nvidia graphics card or maybe someone can make a driver like nouveau

- Mic
Again,  It may never work. Or someone ports a driver from Linux.

- CPU Performance
Use [CPUFriendFriend](https://github.com/corpnewt/CPUFriendFriend) to generate your own `CPUFriendDataProvider.kext`, when it asks you about `Energy Performance Preference (EPP)`, type `0x00 (Performance)`. This option will give you the best performance, and of course, the worst battery life.

Congrats! Now enjoy your not-so-perfecto Hackintosh.

**Comment by imad1505** [comment]
Ciao grazie per la condivisione della EFI ma lo provata sul mio appena parte si ferma?
