### ISSUE TITLE
devices config all same        issues on touchpad    battery    system sleep black screen

### ISSUE THREAD

**Issue by git-small-hub** [lunjielee/Opencore-HP-Omen-15-2020#13]
我尝试了你的配置文件，但是在我的电脑上不起作用。直接进不去系统。我只是将你的ssdt补丁用在我的配置文件中，即使这样也会导致无法进入系统。我的笔记本电脑是惠普光影精灵6 max，pavilion 6 max。我想我们的硬件型号是差不多的，我看到了你的配置，一模一样。我需要把你的触摸板，电池，休眠补丁移植过来，看看他们是不是会起作用。你可以给我一些建议吗？触摸板的bios名称：\_SB.PCI0.I2C1.TPD0
资源类型：IRQ  0x0000003F(63)

I tried your profile, but it doesn't work on my computer. You can't get into the system directly. I'm just using your ssdt patch in my profile, even if that makes it impossible to get into the system. My laptop is HP Light and Shadow Genie 6 max, pavilion 6 max. I think our hardware model is similar, I see your configuration, exactly the same. I need to transplant your touchpad, battery, sleep patches and see if they work. Can you give me some advice?
touchpad bios name：\_SB.PCI0.I2C1.TPD0
resources type：IRQ  0x0000003F(63)

	
电脑型号	HP Pavilion Gaming Laptop 16-a0xxx 
操作系统	Windows 10 专业版 64位 ( DirectX 12 )
	
处理器	英特尔 Core i7-10750H @ 2.60GHz 六核
主板	        惠普 87AE ( LPC Controller - 068D )
内存  	16 GB ( 三星 DDR4 3200MHz )
主硬盘	三星 MZVLB512HBJQ-000H1 ( 512 GB / 固态硬盘 )
主显卡	Nvidia GeForce GTX 1650 Ti ( 4 GB / 惠普 )
显示器	奇美 CMN1605 ( 16 英寸  )
声卡 	英特尔 英特尔智音技术音频控制器
声卡         Nvidia High Definition Audio 控制器
网卡	        英特尔 Wi-Fi 6 AX201 160MHz
网卡         瑞昱 RTL8168/8111/8112 Gigabit Ethernet Controller
keyborad&touchpad
键盘                HID 标准键盘
键盘                HID 标准键盘
 键盘                PS/2 标准键盘
 鼠标                HID-compliant 鼠标
 鼠标                ELAN Input Device
 鼠标                HID-compliant 鼠标
[ssdt.zip](https://github.com/lunjielee/Opencore-HP-Omen-15-2020/files/6090952/ssdt.zip)
[OC.zip](https://github.com/lunjielee/Opencore-HP-Omen-15-2020/files/6090957/OC.zip)
[when you download accompolish,rename to oc.z02.zip](https://github.com/lunjielee/Opencore-HP-Omen-15-2020/files/6090987/when.you.download.accompolish.rename.to.oc.z02.zip)
[when you download accompolish,rename to oc.z01.zip](https://github.com/lunjielee/Opencore-HP-Omen-15-2020/files/6090988/when.you.download.accompolish.rename.to.oc.z01.zip)

**Comment by git-small-hub** [comment]
我的联系方式：1319522961@qq.com
contact me with:1319522961@qq.com

**Comment by lunjielee** [comment]
你好， @git-small-hub，

的确，你的电脑应该只是我的升级版，照理来说应该是可以直接进入的，你把你的dsdt dump一份发给我吧，我看看是不是因为有些设备的路径对不上

**Comment by git-small-hub** [comment]
[ssdt.zip](https://github.com/lunjielee/Opencore-HP-Omen-15-2020/files/6145310/ssdt.zip)

**Comment by lunjielee** [comment]
你好， @git-small-hub ，
看一下最新的给你的设备创建的branch，打了触控板补丁但是没有电池补丁。使用之前一定要用一块pm981a以外的ssd才能启动
