### ISSUE TITLE
兄弟，你的核显难道没被屏蔽吗？

### ISSUE THREAD

**Issue by izbin7** [lunjielee/Opencore-HP-Omen-15-2020#15]
我的机型是HP 暗影精灵6 Air RTX-2060
windows设备管理器里面看不到核显，据说是官方直接底层屏蔽了，用你的EFI，刚跑码就黑屏了。
你的机器核显能正常驱动吗？

**Comment by lunjielee** [comment]
你好， @izbin7,
暗影精灵有两种显卡驱动模式，混合和直通，请下载HP Omen Gaming Hub进行切换。或者进入BIOS进行切换

**Comment by izbin7** [comment]
你好，我的这个机型Omen Gaming Hub中没有显卡的选项，BIOS也没有相关设置，估计是凉了

**Comment by lunjielee** [comment]
那还是暗影精灵6 Air高端😂
