### ISSUE TITLE
Kernel Panic restart on Big Sur install

### ISSUE THREAD

**Issue by adnanmur** [lunjielee/Opencore-HP-Omen-15-2020#16]
Hi, 

I have a same config except i have 2070.

I used your efi to set everything up but upon booting from USB, the system automatically reboots on Kernel Panic and its fast I cant read what it says but the errors that occur mostly are that the disks4 is write protected and the last thing that caught my eye is applenvme request something and then it halts and reboots.

I have a hackintosh running for 4 years now but its a desktop, I'm out of a loop a little bit with opencore as it works perfectly on my pc and I'm just updating it.

I would appreciate any help here.

Please note that I am using two ssds, one for windows and the other one for hackintosh.

**Comment by Warmerfare** [comment]
Hey @adnanmur ,

Have you tried disabling the stock samsung m2 disk yet? In the default config.plist this patch is not enabled.

Do a lookup for (ctrl + F) "Disable PM981a" inside of the config.plist and change false to true.

Try booting again after this change, you should be good to go.
