### ISSUE TITLE
When i don't patch graphic, Laptop boots but when i do it doesn't

### ISSUE THREAD

**Issue by yusufklncc** [lunjielee/Opencore-HP-Omen-15-2020#18]

**Comment by taurzon5** [comment]
Please provide some details about the relevant hardware and Opencore Configuration.

**Comment by yusufklncc** [comment]
My Specs:
OpenCore 0.6.8
HP OMEN 15-ek0003nt 2020 
Intel Core i7 10750H Comet Lake
Intel HD Graphics 630 & Nvdia RTX 2070 with Max-Q Design
Realtek RLT8168/8111 & Intel Wi-Fi 6 AX201
WD PC SN730 1TB NVMe SSD & 8*2 DDR4 2933MHz 

i am using ur EFI folder. But laptop won't boot with graphic card patch. When i remove the graphics card patch it boots.
Can you share ur BIOS setting or Did this happen to you too?

**Comment by taurzon5** [comment]
I have a GTX 1650 Ti and it works fine for me. Did you try building your own patch. Here https://dortania.github.io/OpenCore-Install-Guide/extras/spoof.html 
Try following this guide.
I believe you are trying to disable NVIDIA GPU.

**Comment by yusufklncc** [comment]
No, i disabled with disable-external-gpu.  i am trying to do intel graphic patch but laptop wont boot.

**Comment by taurzon5** [comment]
On the page https://dortania.github.io/OpenCore-Install-Guide/config-laptop.plist/coffee-lake-plus.html#deviceproperties see for deviceproperties section and then see what they did there for Intel iGPU. Hope it helps.
