### ISSUE TITLE
哥们，WiFi和雷电正常不?

### ISSUE THREAD

**Issue by laughcool** [lunjielee/Opencore-HP-Omen-15-2020#2]
请问下，
1.WiFi稳定不？还有蓝牙能正常使用吗？

2. 雷电接口能使用吗？如果还没解决，这个雷电有希望解决吗，我打算用雷电接双屏

如果我购买，同样机型，2070的版本应该你这个配置也能用的吧？

希望有空回答下，多谢啦！

**Comment by lunjielee** [comment]
你好，这款机器的集成显卡是没有办法输出的，所有的接口都接在了独立显卡上
Wifi的话（焊死的，换不了）感谢[@zxystd](https://github.com/zxystd)写的[AirportItlwm](https://github.com/OpenIntelWireless/itlwm)与[IntelBluetoothFirmware](https://github.com/OpenIntelWireless/IntelBluetoothFirmware)是可以正常使用的，包括蓝牙
WiFi的速度和windows下的速度还是有差别的
同样的机型应该是可以使用的
