### ISSUE TITLE
部分系统软件打不开（闪退提示意外退出）

### ISSUE THREAD

**Issue by Wilber666** [lunjielee/Opencore-HP-Omen-15-2020#20]
兄弟，您好，我的机型是暗夜精灵6，i5-10500h+gtx1650，用您的EFI成功安装catalina 但是系统自带的照片app，imovie，Clion编程软件打开闪退并报错，微信登录后也出现了同样的情况。后来在安全模式下发现可以打开app，切换到正常模式后又闪退了

**Comment by lunjielee** [comment]
额，这问题挺蹊跷，你目前的macOS版本是多少呢？（包括小版本）。以及报错时的截图能发一下吗？

**Comment by Wilber666** [comment]
<img width="1424" alt="截屏2021-06-23 上午11 58 49" src="https://user-images.githubusercontent.com/62875848/123033791-e91a8680-d41a-11eb-99c3-8ba20d895ff3.png">
<img width="1424" alt="截屏2021-06-23 上午11 59 11" src="https://user-images.githubusercontent.com/62875848/123033797-ea4bb380-d41a-11eb-9769-93995634ae12.png">
<img width="1424" alt="截屏2021-06-23 上午11 59 52" src="https://user-images.githubusercontent.com/62875848/123033798-eb7ce080-d41a-11eb-946c-cf0a0c31e6cf.png">
<img width="1424" alt="截屏2021-06-23 上午11 59 30" src="https://user-images.githubusercontent.com/62875848/123033801-ecae0d80-d41a-11eb-91f5-b77f4c4a9852.png">
<img width="1424" alt="截屏2021-06-23 上午11 59 21" src="https://user-images.githubusercontent.com/62875848/123033803-ed46a400-d41a-11eb-9167-e8a8e30592ba.png">
<img width="577" alt="截屏2021-06-23 下午12 25 04" src="https://user-images.githubusercontent.com/62875848/123035836-a490ea00-d41e-11eb-8f2a-ac4ef28279f9.png">

**Comment by lunjielee** [comment]
@Wilber666 你好，
请问您能将上述崩溃应用的问题报告完整的上传到该issue里吗？十分感谢
根据经验判断应该是iGPU的设置存在问题，如果可以的话能否将系统更新到macOS 10.15.7？

**Comment by Wilber666** [comment]
恭喜你猜对啦，今天下午我意外折腾好了，是因为核显id注入错了，重新注入显示uhd630就好了，（以前更新过10.15.7，可惜没解决），谢谢您啦

**Comment by lunjielee** [comment]
> 恭喜你猜对啦，今天下午我意外折腾好了，是因为核显id注入错了，重新注入显示uhd630就好了，（以前更新过10.15.7，可惜没解决），谢谢您啦

恭喜解决🎉
