### ISSUE TITLE
您好 冒昧使用中文提问

### ISSUE THREAD

**Issue by hannaryuu** [lunjielee/Opencore-HP-Omen-15-2020#23]
我的暗影精灵6 配置是
i5-10300h
16gb
gtx1650ti

使用您的EFI总是在进度条走完后出现禁止符号
跑码模式看 好像是核显无法驱动

请问有什么办法驱动i5的核显吗

**Comment by lunjielee** [comment]
您好，
您可以试一下readme里提到的注入参数，看看是否能驱动

**Comment by hannaryuu** [comment]
您好 感谢回复

注入参数尝试过 问题依旧

**Comment by lunjielee** [comment]
> 您好 感谢回复
> 
> 注入参数尝试过 问题依旧

Hi,
你可以看一下这个配置文件[Legion-5i-EFI](https://github.com/LuckyCrack/Legion-5i-EFI)，尝试伪装cpu为i7 8750H
机器的配置和你的应该是一摸一样的。

![Screen Shot 2021-08-19 at 11 19 49 AM](https://user-images.githubusercontent.com/32808108/130002442-dc6198a9-fd02-45f0-a81c-7a2cbfe8461b.png)
