### ISSUE TITLE
Menu entry for install

### ISSUE THREAD

**Issue by rikr2sanchez** [lunjielee/Opencore-HP-Omen-15-2020#24]
Hi ! 
Thanks for sharing the configuration. I want to install from USB but I cant see the install entry in the boot Menu, I have just one entry (Windows).

**Comment by lunjielee** [comment]
Hi @rikr2sanchez,
have you tried to add `HfsPlus.efi` under the `EFI/OC/Drivers` folder

**Comment by rikr2sanchez** [comment]
Already there

**Comment by lunjielee** [comment]
Hi @rikr2sanchez,
please referring to this guide from **dortania** to make a macOS installer in a USB stick under Windows: [Making the installer in Windows](https://dortania.github.io/OpenCore-Install-Guide/installer-guide/winblows-install.html)

**Comment by jogiji** [comment]
Hit space key when you are at boot menu.

**Comment by rikr2sanchez** [comment]
Already installed after few fix in the kexts. Only thing (fixable) that doesn't work : need to wait 5 minutes after boot for the backlight.

**Comment by rikr2sanchez** [comment]
> Already installed after few fix in the kexts. Only thing (fixable) that doesn't work : need to wait 5 minutes after boot for the backlight.

@lunjielee did you experienced this behavior before ??.

**Comment by Wilber666** [comment]
谢谢哥，辛苦了


发自我的iPhone
