### ISSUE TITLE
Monterey Ready?

### ISSUE THREAD

**Issue by jogiji** [lunjielee/Opencore-HP-Omen-15-2020#27]
Hi @lunjielee .. just curious are you still using your machine and have you upgraded to Monterey using the efi that you have here?
I am facing difficulties upgrading it.

**Comment by rikr2sanchez** [comment]
Hi @jogiji could you fix the backlight?

**Comment by jogiji** [comment]
Successfully upgraded to Monterey.. so closing this issue.
