### ISSUE TITLE
I can't use bluetooth

### ISSUE THREAD

**Issue by Brian-Du** [lunjielee/Opencore-HP-Omen-15-2020#28]
hi. my pc is omen 15 2020
10750h 1650ti 16gb
I have successfully installed the macOS  on my pc, but the bluetooth doesn't work.
I asked some people, they told me that maybe usb is not customized. But when I open Hackintool , the App can't show me the USB ports. So I can't  do that, either.
What is the problem of the bluetooth on my pc
<img width="301" alt="QQ20220127-152321@2x" src="https://user-images.githubusercontent.com/82600685/151311927-18a80809-e7f3-4e1b-a993-7fc06bc740c9.png"><img width="656" alt="image" src="https://user-images.githubusercontent.com/82600685/151312003-8a82997b-7593-4a90-b82e-18a8d47bf510.png">

**Comment by Brian-Du** [comment]
the version of macOS is 12.2

**Comment by eugene2878** [comment]
You need to use USBtoolBox to get  your custom USB ports list since no USBports.kext provided. Alternatively USBPorts.kext may work from this [repo ](https://github.com/swq93/HP-Omen-15-2020-ek0000-OC-efi)

**Comment by Brian-Du** [comment]
OK, I will try

**Comment by lunjielee** [comment]
@eugene2878 Thanks for your help in replying to the issue, I'll close this for now
