### ISSUE TITLE
ALC256 

### ISSUE THREAD

**Issue by abdllhcrk** [lunjielee/Opencore-HP-Omen-15-2020#5]
Hello, can you help me to add New codec support for ALC256 ? I tried everything but i really don't know what to do. If you want, I can send my Codec Dump file.

**Comment by lunjielee** [comment]
Sure boot your device with Ubuntu live system and make sure the sound is working properly then dump your codec files and run this command after you plug in and plug out your headphone`dmesg | grep snd_hda_codec_realtek > availablenodes.txt` archive them all and upload here

**Comment by abdllhcrk** [comment]
Thank you so much for your help. I am using Acer Swift 3 laptop. I tried all layouts for ALC256.  With 21 and 66 layouts, speakers are working well and Internal Mic is recognized by system but mic not working. Actually I need your help for my Built in Internal Mic.

[codec dump.zip](https://github.com/lunjielee/Opencore-HP-Omen-15-2020/files/5516896/codec.dump.zip)

**Comment by lunjielee** [comment]
if your built in mic uses intel smart sound technology then you can't use them in macOS cause they are not supported currently

**Comment by abdllhcrk** [comment]
Yes my mic use Intel Smart Sound Technology so for now it won't work right ? Is it possible that will have support for Intel Smart Sound in the future ?

**Comment by lunjielee** [comment]
> Yes my mic use Intel Smart Sound Technology so for now it won't work right ? Is it possible that will have support for Intel Smart Sound in the future ?

yes the mic won't work right now, and we will have to wait after apple release their 10th gen mac to find out what's going on
