### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by 9and3r** [lunjielee/Opencore-HP-Omen-15-2020#7]
I am trying to install Mac Os on the same laptop.
 
I created the USB installation media using this tutorial [this tutorial](https://dortania.github.io/OpenCore-Install-Guide/installer-guide/winblows-install.html) but I used your files for the EFI folder instead. I changed the config.plist file to set HideAuxiliary to false and set the timeout to 15. 

Then I was able to select the instalation media and the Apple logo appears on the screen and the progressbar start to fill, but when the bar is on 25% aproximately the computer reboots.

Should I use diferent files for instalation or do you have a tutorial to follow?

Thanks for all the work you have allready done!

**Comment by lunjielee** [comment]
Are you using the pm981 ssd?

**Comment by 9and3r** [comment]
Hi.

I have used the second slot to install a 500 GB samsung 970 evo plus and I would like to install Mac OS X there. 
In the primary slot, I have the original SSD with Windows installed that it is the PM981a.

The problem is that I was unable to reach the installation screen so I did not select what SSD to use.

Thanks for your help.

**Comment by lunjielee** [comment]
according to dortania's guide, you need to upgrade your SSD's firmware in order to use it in macOS

here is the link: [https://dortania.github.io/Anti-Hackintosh-Buyers-Guide/Storage.html](url)

**Comment by 9and3r** [comment]
Hi again.

I tried botting without any SSD installed just in case and the same problem appears. 
I noticed that my nvidia card is 2070 Max Q instead of the 2060 (Maybe this is the issue).

Thanks
