### ISSUE TITLE
Help with my laptop.

### ISSUE THREAD

**Issue by DCuchillas** [lunjielee/Opencore-HP-Omen-15-2020#8]
Hey, I have similar model but is Hp Pavilion Gaming 15-dk1027la , running processor i7-10750H and NVidia GTX1650. 

I tried following the opencore guide but I end up on ACPI errors, using dsdt built with SDTTime, and I tried using your EFI but same errors, tried replacing my aml along with yours but couldn't get anywhere. 

Please, can you help me, I'm desperate trying to get Catalina to work with my laptop.

**Comment by lunjielee** [comment]
I might need your dsdt and ssdt dumps, and maybe a picture of your laptop while ACPI errors appear
