### ISSUE TITLE
Suggestion--> Adding NO d-GPU related aml files increases battery life

### ISSUE THREAD

**Issue by jogiji** [lunjielee/Opencore-HP-Omen-15-2020#9]
@lunjielee  I am not pretty sure but when i added d-GPU related ACPI files to your config .. I am able to observe a jump in battery life... This may be a pure load based issue also.. I would advice you try it once.

**Comment by lunjielee** [comment]
Well, thanks a lot that did help with solving the problem, thanks again and happy holidays!
